#application.properties rename to application.yml

server:
  port: 8761  #Eureka가 Web Service의 성격으로 기동하고자 할때 설정할 PORT 번호 지정

spring:
  application:
    name: discoveryservice

#eureka 라이브러리가 포함된채 스프링부트가 기동이 되면 기본적으로 eureka client 역할로써
#register-with-eureka, fetch-registry에 등록하려고 하는데 이를 막기 위한 설정 추가
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false